### ISSUE TITLE
Original models

### ISSUE THREAD

**Issue by mike-engel** [jyojoh/case-designs#1]
Hi! Thank you for providing these cases! I need to make a few modifications for accommodate a slightly larger 600mAh battery, and it would be much easier if I had access to the original design files.

Thanks!

**Comment by mike-engel** [comment]
Realized the `step` files represent the solid bodies and can be used as the source 🤦

**Comment by jyojoh** [comment]
The "standard" cases are already capable of housing a battery with a capacity larger than 600mAh, they accommodate the  803450 batteries which are typically rated at around 1600mAh

**Comment by mike-engel** [comment]
Printing the legged version, my battery is apparently an odd size. Even though it's 600mAh, but it's wider than what's currently designed. Thanks again for making these!
